// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetP, TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYlP9LFYeoWikoBDFi79lzncGBiXgE6iE',
    appId: '1:856779613218:web:29d78491510bce0c61167b',
    messagingSenderId: '856779613218',
    projectId: 'apppolitimetrica-8c73f',
    authDomain: 'apppolitimetrica-8c73f.firebaseapp.com',
    storageBucket: 'apppolitimetrica-8c73f.firebasestorage.app',
    measurementId: 'G-R95N2YGC5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACtLNKQ_VQFPxNS3XFImZEC7yKM2EIWbI',
    appId: '1:856779613218:android:39344cdb63e3463e61167b',
    messagingSenderId: '856779613218',
    projectId: 'apppolitimetrica-8c73f',
    storageBucket: 'apppolitimetrica-8c73f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXESuRHJDjqIvVGMEqC23uOt8PQriRE4s',
    appId: '1:856779613218:ios:1ee117bc32fb806d61167b',
    messagingSenderId: '856779613218',
    projectId: 'apppolitimetrica-8c73f',
    storageBucket: 'apppolitimetrica-8c73f.firebasestorage.app',
    iosBundleId: 'com.example.appPolitimetrica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXESuRHJDjqIvVGMEqC23uOt8PQriRE4s',
    appId: '1:856779613218:ios:1ee117bc32fb806d61167b',
    messagingSenderId: '856779613218',
    projectId: 'apppolitimetrica-8c73f',
    storageBucket: 'apppolitimetrica-8c73f.firebasestorage.app',
    iosBundleId: 'com.example.appPolitimetrica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYlP9LFYeoWikoBDFi79lzncGBiXgE6iE',
    appId: '1:856779613218:web:cad859b682bf64cd61167b',
    messagingSenderId: '856779613218',
    projectId: 'apppolitimetrica-8c73f',
    authDomain: 'apppolitimetrica-8c73f.firebaseapp.com',
    storageBucket: 'apppolitimetrica-8c73f.firebasestorage.app',
    measurementId: 'G-FVK8ED9C2B',
  );
}
